# Generated by Django 3.2.8 on 2021-10-30 13:24

import datetime
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ab', '0006_alter_sensor_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='data',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='when',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 30, 13, 24, 26, 400058)),
        ),
    ]
