# Generated by Django 3.2 on 2021-10-24 14:44

import datetime
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 24, 14, 44, 58, 310150))),
                ('data', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
    ]
